mode: deployment

image:
  repository: otel/opentelemetry-collector-contrib
  tag: "0.156.0"

command:
  name: otelcol-contrib

config:
  exporters:
    debug: {}
    otlp_grpc/tempo:
      endpoint: tempo.shopops-dev.svc.cluster.local:4317
      tls:
        insecure: true
    
    otlp_http/loki:
      endpoint: http://loki.shopops-dev.svc.cluster.local:3100/otlp
      tls:
        insecure: true

    prometheus:
      endpoint: 0.0.0.0:8889

  service:
    pipelines:
      traces:
        receivers:
          - otlp
        processors:
          - memory_limiter
          - batch
        exporters:
          - debug
          - otlp_grpc/tempo

      metrics:
        receivers:
          - otlp
        processors:
          - memory_limiter
          - batch
        exporters:
          - debug
          - prometheus

      logs:
        receivers:
          - otlp
        processors:
          - memory_limiter
          - batch
        exporters:
          - debug
          - otlp_http/loki

ports:
  prometheus:
    enabled: true
    containerPort: 8889
    servicePort: 8889
    protocol: TCP

resources:
  requests:
    cpu: 100m
    memory: 128Mi

  limits:
    cpu: 250m
    memory: 256Mi