apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector-dev
  namespace: argocd

spec:
  project: default

  sources:
    - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      chart: opentelemetry-collector
      targetRevision: 0.165.0
      helm:
        valueFiles:
          - $values/deploy/environments/dev/otel-collector/values.yaml
        releaseName: otel-collector

    - repoURL: https://github.com/rid1lawal/shopops.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: shopops-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
