replicaCount: 1

image:
  tag: "e63c6c9817a0cf2afdcc1b868e82352614ff7962"

config:
  httpPort: "8080"
  environment: "dev"
  otlpEndpoint: "otel-collector-opentelemetry-collector.shopops-dev.svc.cluster.local:4317"
  serviceName: "catalog"

database:
  existingSecret: "catalog-db"
  existingSecretKey: "DATABASE_URL"

resources:
  requests:
    cpu: 100m
    memory: 128Mi

  limits:
    cpu: 250m
    memory: 256Mi

aws:
  region: "eu-west-1"