replicaCount: 1
image:
  tag: "a3c256ed109b845942b17c864f6fd17012000a6d"
config:
  httpPort: "8080"
  environment: "dev"
  otlpEndpoint: "otel-collector-opentelemetry-collector.shopops-dev.svc.cluster.local:4317"
  serviceName: "catalog"
azure:
  workloadIdentity:
    clientId: "85b91f72-eb63-4bec-ae16-d8874eb4a748"
  keyVault:
    name: "shopops-dev-kv"
    tenantId: "59077572-066a-4769-b3b7-d6a75d5e5768"
database:
  existingSecret: "catalog-db"
  existingSecretKey: "DATABASE_URL"
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
