replicaCount: 1
image:
  tag: "order-d1e320406da6afeb0d8ac6919620356b17d42f1c"
config:
  httpPort: "8090"
  environment: "dev"
  otlpEndpoint: "otel-collector-opentelemetry-collector.shopops-dev.svc.cluster.local:4317"
  serviceName: "order"
  catalogServiceUrl: "http://catalog.shopops-dev.svc.cluster.local:8080"
database:
  existingSecret: "order-db"
  existingSecretKey: "DATABASE_URL"
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
aws:
  region: "eu-west-1"
