apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "catalog.fullname" . }}
  labels:
    {{- include "catalog.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      {{- include "catalog.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "catalog.selectorLabels" . | nindent 8 }}

    spec:
      containers:
        - name: catalog
          image: "{{ .Values.image.repository }}:{{ required "image.tag must be set" .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP

          resources:
            {{- toYaml .Values.resources | nindent 12 }}