apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "catalog.fullname" . }}
  labels:
    {{- include "catalog.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      {{- include "catalog.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "catalog.selectorLabels" . | nindent 8 }}
        azure.workload.identity/use: "true"

    spec:
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ include "catalog.fullname" . }}-secrets
      serviceAccountName: {{ include "catalog.fullname" . }}
      containers:
        - name: catalog
          image: "{{ .Values.image.repository }}:{{ required "image.tag must be set" .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          volumeMounts:
            - name: secrets-store
              mountPath: /mnt/secrets-store
              readOnly: true

          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP

          env:
            - name: HTTP_PORT
              value: {{ .Values.config.httpPort | quote }}

            - name: ENVIRONMENT
              value: {{ .Values.config.environment | quote }}

            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.config.otlpEndpoint | quote }}

            - name: SERVICE_NAME
              value: {{ .Values.config.serviceName | quote }}

            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.existingSecret }}
                  key: {{ .Values.database.existingSecretKey }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}