apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "catalog.fullname" . }}-db
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: {{ include "catalog.fullname" . }}-secretstore
    kind: SecretStore

  target:
    name: {{ .Values.database.existingSecret }}
    creationPolicy: Owner

  data:
    - secretKey: {{ .Values.database.existingSecretKey }}
      remoteRef:
        key: DB_URL