apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ include "catalog.fullname" . }}-secretstore
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.aws.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "catalog.serviceAccountName" . }}