apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "catalog.fullname" . }}
  labels:
    {{- include "catalog.labels" . | nindent 4 }}
  annotations:
    azure.workload.identity/client-id: {{ required "azure.workloadIdentity.clientId must be set" .Values.azure.workloadIdentity.clientId | quote }}