name: Catalog CI

on:
  push:
    branches:
      - main
    paths:
      - "services/catalog/**"

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: eu-west-1
  ECR_REPOSITORY: shopops
  IMAGE_TAG: ${{ github.sha }}

jobs:
  test-and-build:
    name: Test, Build and Push
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/catalog

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: services/catalog/go.mod
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Catalog image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build \
            -f docker/catalog/Dockerfile \
            -t "$REGISTRY/$ECR_REPOSITORY/catalog:$IMAGE_TAG" \
            .

          docker push "$REGISTRY/$ECR_REPOSITORY/catalog:$IMAGE_TAG"